name: Atualizar Painel da Copa 2026

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

# FORÇA O GITHUB A ACEITAR A ESCRITA VIA CÓDIGO
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Clonar o Repositório
      uses: actions/checkout@v4

    - name: 2. Configurar o Python no Servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalar Dependências de Raspagem
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: 4. Executar o Script de Atualização
      working-directory: copa
      run: python copa26.py

    - name: 5. Enviar alterações e dar o Push de volta para o GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Como estamos na raiz, adicionamos apontando o caminho completo da pasta
        git add copa/copa.html
        
        # Verifica alterações de forma segura na raiz
        if ! git diff-index --quiet HEAD; then
          git commit -m "🤖 [Bot] Placares da Copa Atualizados via Python"
          git push origin main
        else
          echo "Nenhum resultado novo encontrado. O arquivo já está atualizado."
        fi