name: Atualizar Painel da Copa 2026

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o Repositório
      uses: actions/checkout@v4

    - name: Configurar o Python no Servidor
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalar Dependências de Raspagem
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    # Ajustado: adicionado o working-directory para entrar na pasta 'copa'
    - name: Executar o Script de Atualização
      working-directory: copa
      run: python copa26.py

    # Ajustado: adicionado o working-directory para commitar a partir de 'copa'
    - name: Enviar alterações e dar o Push de volta para o GitHub Pages
      working-directory: copa
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git add copa.html
        git diff-index --quiet HEAD || git commit -m "🤖 [Bot] Placares da Copa Atualizados via Python"
        git push